// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3_TPIxaBDDJEaW50j-Fmimf0M2kiWDoU',
    appId: '1:613300579527:web:882e4ea0b51b066611e2e2',
    messagingSenderId: '613300579527',
    projectId: 'todo-c10-4sun',
    authDomain: 'todo-c10-4sun.firebaseapp.com',
    storageBucket: 'todo-c10-4sun.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs7pU4FxeZBnSrmtOv5YEVV7hGNX0nScc',
    appId: '1:613300579527:android:4c1fa83e45090b5111e2e2',
    messagingSenderId: '613300579527',
    projectId: 'todo-c10-4sun',
    storageBucket: 'todo-c10-4sun.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEQ9pZ3pR5RYOjB5k787snak542bVkvPk',
    appId: '1:613300579527:ios:b5dbc03abce722db11e2e2',
    messagingSenderId: '613300579527',
    projectId: 'todo-c10-4sun',
    storageBucket: 'todo-c10-4sun.appspot.com',
    iosBundleId: 'com.example.todoAppC10Sun4pm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEQ9pZ3pR5RYOjB5k787snak542bVkvPk',
    appId: '1:613300579527:ios:c2c21630a0f3c30111e2e2',
    messagingSenderId: '613300579527',
    projectId: 'todo-c10-4sun',
    storageBucket: 'todo-c10-4sun.appspot.com',
    iosBundleId: 'com.example.todoAppC10Sun4pm.RunnerTests',
  );
}
